// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Style_Template_EFCore_OnThi.Models;

namespace Style_Template_EFCore_OnThi.Migrations
{
    [DbContext(typeof(QLBanHang1Context))]
    partial class QLBanHang1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Vietnamese_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Style_Template_EFCore_OnThi.Models.HoaDonChiTiet", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("MaHD")
                        .IsFixedLength(true);

                    b.Property<string>("MaSp")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("MaSP")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("NgayBan")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuongMua")
                        .HasColumnType("int");

                    b.HasKey("MaHd", "MaSp")
                        .HasName("PK__HoaDonCh__F557F6613FA27083");

                    b.HasIndex("MaSp");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("Style_Template_EFCore_OnThi.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("MaKH")
                        .IsFixedLength(true);

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("GioiTinh")
                        .IsFixedLength(true);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("HoTen")
                        .IsFixedLength(true);

                    b.HasKey("MaKH")
                        .HasName("PK_KhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Style_Template_EFCore_OnThi.Models.LoaiSp", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength(true);

                    b.Property<string>("TenLoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiSP__730A575989486C3B");

                    b.ToTable("LoaiSP");
                });

            modelBuilder.Entity("Style_Template_EFCore_OnThi.Models.SanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("MaSP")
                        .IsFixedLength(true);

                    b.Property<int?>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("MaLoai")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength(true);

                    b.Property<int?>("SoLuongCo")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C539B0877");

                    b.HasIndex("MaLoai");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("Style_Template_EFCore_OnThi.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("Style_Template_EFCore_OnThi.Models.SanPham", "MaSpNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK__HoaDonChiT__MaSP__29572725")
                        .IsRequired();

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("Style_Template_EFCore_OnThi.Models.SanPham", b =>
                {
                    b.HasOne("Style_Template_EFCore_OnThi.Models.LoaiSp", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__SanPham__MaLoai__267ABA7A");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("Style_Template_EFCore_OnThi.Models.LoaiSp", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Style_Template_EFCore_OnThi.Models.SanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
